### ISSUE TITLE
Planning Is Hard

### ISSUE THREAD

**Issue by al-the-x** [TIY-Durham/TIY-Catalog#1]
- [ ] Identify _features_ for [the "Trending" page](https://etsy.com/trending)
- [ ] Identify _features_ for a Product page:
  - https://www.etsy.com/listing/184452971/the-modern-rocking-chair
  - https://www.etsy.com/listing/162994765/classic-buffalo-leather-briefcase
  - https://www.etsy.com/listing/89288680/monogram-napa-leather-case-for-macbook
- [ ] Identify _features_ for a Category page:
  - https://www.etsy.com/c/bags-and-purses/messenger-bags
  - Any others?

**Comment by ShayHall** [comment]
**Master List of Issues**

**Comment by al-the-x** [comment]
Some big holes in this plan, @TIY-Durham/2015-fall-fee. If you're working on a feature, please adjust the comment appropriately and / or link your _WIP Issue_ (in _this_ repo) back to _this_ issue!

**Comment by Ricecoder** [comment]
Here is my issue:
https://github.com/TIY-Durham/TIY-Catalog/issues/5

**Comment by ShayHall** [comment]
https://github.com/TIY-Durham/TIY-Catalog/issues/9

**Comment by jeremyrist** [comment]
https://github.com/TIY-Durham/TIY-Catalog/issues/14

**Comment by karjac14** [comment]
Product Page: feature--item-tabs: 
![feature-item-tabs-01](https://cloud.githubusercontent.com/assets/8317978/10444738/9f5cf6be-7137-11e5-8edf-03e7eefef194.png)
![feature-item-tabs-02](https://cloud.githubusercontent.com/assets/8317978/10444739/9f5d2576-7137-11e5-9a91-ca53e9473d91.png)

**Comment by karjac14** [comment]
Product Page: feature--item-detail-panel: 
![feature-item-details-panel](https://cloud.githubusercontent.com/assets/8317978/10444756/c7db6dd2-7137-11e5-989f-a487ac8f4e8f.png)

**Comment by jeffworley** [comment]
[Master List of Features](https://github.com/TIY-Durham/TIY-Catalog/wiki)

**Comment by jeffworley** [comment]
[Division of Feature Labor & Agreed Upon Naming Conventions](https://github.com/TIY-Durham/TIY-Catalog/wiki/Division-of-Feature-Labor-&-Agreed-Upon-Naming-Conventions)
