### ISSUE TITLE
How should we name all these Skitch notes?

### ISSUE THREAD

**Issue by al-the-x** [TIY-Durham/TIY-Catalog#30]
@TIY-Durham/2015-fall-fee How do you think we should name all of our Skitch notes in `specs/`... 'Cause dey gittin' outta control!

@ericquayson Made some suggestions on #29 to consider. Who else has some ideas?

**Comment by al-the-x** [comment]
@jeffworley Toss me a link to that wiki page?

**Comment by jeffworley** [comment]
[Here it is!](https://github.com/TIY-Durham/TIY-Catalog/wiki/Division-of-Feature-Labor-&-Agreed-Upon-Naming-Conventions)  Please look at the bottom to see naming conventions and let the group know if anyone makes changes :smile:
